### ISSUE TITLE
Broken when deployed with GH Pages

### ISSUE THREAD

**Issue by banesullivan** [rtfd/sphinx-notfound-page#12]
We recently had to migrate the docs for [`vtki`](http://docs.vtki.org) over to GitHub pages from readthedocs because we're now using the [sphinx-gallery](https://sphinx-gallery.github.io) extension to create [an epic examples page](http://docs.vtki.org/examples/index.html)!

Unfortunately, readthedocs can't handle setting up all the dependencies we need to actually run `vtki` (or least it's not clear how we could do this). This means all the `sphinx-notfound-page` links are broken because the assume the `en/latest` phrase is prefixed to all pages.

For example check out this 404 page: http://docs.vtki.org/foo

<img width="650" alt="Screen Shot 2019-04-05 at 12 59 33 PM" src="https://user-images.githubusercontent.com/22067021/55650590-60649100-57a3-11e9-8b6d-1864d695d055.png">

All the links in the sidebar go to 404 pages as well....

**Comment by humitos** [comment]
Hi!

Yes. This extension was thought to handle 404 on Read the Docs.

There are some small configs where you can define the language and version but I think it will still add something to the URLs.

I can accept a PR that handle this case (outside RTD).

> Unfortunately, readthedocs can't handle setting up all the dependencies we need to actually run vtki (or least it's not clear how we could do this)

Did you open an issue on RTD? This should not be a problem at first sight.

**Comment by banesullivan** [comment]
> I can accept a PR that handle this case (outside RTD).

I'll see if I can hack a solution together for this

> Did you open an issue on RTD? This should not be a problem at first sight.

Either way I think we're going to stick with deploying to GHPages from Travis - the build environment and status reporting is just way better the readthedocs.org
