### ISSUE TITLE
Tag release for 0.2.1

### ISSUE THREAD

**Issue by banesullivan** [rtfd/sphinx-notfound-page#15]
Can you tag a release for version 0.2.1 - it looks like this was forgotten after 0137c8e

**Comment by banesullivan** [comment]
Asking because I have quite a few projects using this AWESOME plugin that have to install from the master branch when building the docs on CI services

**Comment by banesullivan** [comment]
Oh whoops, I didn't realize 0.2.1 was pushed to PyPI: https://pypi.org/project/sphinx-notfound-page/#history ...I only looked at the tags on GitHub

Its good practice to make sure the Git tags match the deployed releases... also, if you are manually deploying this to PyPI, I could implement a Travis CI script to handle all that for you

**Comment by humitos** [comment]
> Can you tag a release for version 0.2.1 - it looks like this was forgotten after [0137c8e](https://github.com/rtfd/sphinx-notfound-page/commit/0137c8e829fe3e5dab362e9dc957ac5c975db18e)

I just tagged it.

> Asking because I have quite a few projects using this AWESOME plugin that have to install from the master branch when building the docs on CI services

May I ask where are you using it? I'm interested where and how it's used :)

> also, if you are manually deploying this to PyPI, I could implement a Travis CI script to handle all that for you

That could be pretty handy. Although, I don't think it worth your time considering that I'm not deploying too many releases :)

**Comment by banesullivan** [comment]
> May I ask where are you using it? I'm interested where and how it's used :)

Mostly with [PyVista](https://github.com/pyvista/pyvista) - check out this 404 page 😄 : https://docs.pyvista.org/examples/foo

I'm working to get this plugin used with ~10 other projects soon here but in the meantime, check out your dependency graph: https://github.com/rtfd/sphinx-notfound-page/network/dependents

**Comment by humitos** [comment]
Thanks! I'm closing the issue since the tag is already done.
