### ISSUE TITLE
Add badges to the docs homepage and README file

### ISSUE THREAD

**Issue by humitos** [rtfd/sphinx-notfound-page#36]
We want to add PyPI, Travis, Docs, and other budgets that we consider useful.

**Comment by acozine** [comment]
@humitos not sure if #55 closes this or not . . . your call.

**Comment by humitos** [comment]
@acozine do you know why the build badge says "Unknown" but the repo tick is green?

What do you think about adding the same badges in the index file of the docs? #36

**Comment by acozine** [comment]
@humitos if you look at the Travis page itself, the badge there also says "Unknown" in the top banner - that is, the individual build says "Passing" but the overall status of the project above is still "Unknown". I think you may need to change a Travis setting (which I can't access). See the second answer on https://stackoverflow.com/questions/12030304/why-is-my-travis-ci-build-status-always-reflected-as-unknown.

**Comment by acozine** [comment]
Meanwhile I'll see what I can do about adding badges to the docs page.

**Comment by acozine** [comment]
@humitos looks like Travis is running tests but not "builds": https://travis-ci.org/rtfd/sphinx-notfound-page/builds. This closed issue may have relevant information: https://github.com/travis-ci/travis-ci/issues/6932

**Comment by stsewd** [comment]
Guessing something happened when the repo was moved or the privacy was changed?

**Comment by humitos** [comment]
Hrm... I went to the Build History tab in Travis and trigger one manually. Now it shows the proper badge. I also setup a daily build on `master`. Let's see what happen :man_shrugging:
