### ISSUE TITLE
Configuration docs page could be better

### ISSUE THREAD

**Issue by humitos** [rtfd/sphinx-notfound-page#39]
Our configuration page is good, https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html but when I did it I wanted it to look exactly like this one: https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_type

That way is easy to identify the setting immediately but also to use permalinks on them.

**Comment by acozine** [comment]
The look of the configuration page was updated by #45. It's also now possible to link to individual settings like [notfound_pagename](https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html#confval-notfound_pagename). Are there other requirements for this issue?

**Comment by humitos** [comment]
No, your work was amazing! :)

I thought this issue would close automatically but it didn't. Closing now.

Thanks again.
