### ISSUE TITLE
Image path points to wrong directory

### ISSUE THREAD

**Issue by acozine** [rtfd/sphinx-notfound-page#42]
I'm having trouble including an image in my custom 404 page. If I add an image as `docs/docsite/rst/images/foo.png` and a custom 404 file `docs/docsite/rst/404.rst` that looks like this:

```
.. _page_not_found:

Oops!
=====

The page you're looking for doesn't exist in this version of the documentation.

.. image:: images/foo.png
   :alt: Custom 404

Return to the :ref:`index page for this version <index_anchor_name>`.
```

then build the docsite with config settings in the conf.py that look like this:

```
notfound_default_language = "foo"
notfound_default_version = "1.0"
notfound_no_urls_prefix = False
# no value set for notfound_template
# no value set for notfound_context
```

The 404 page gets built, the stylesheets and all toctree links load correctly for pages at any level of the filetree (hooray!). 

However, in the HTML output, Sphinx places the image in a folder called `_static/images/` (and places some other images in a folder called `_images`), but the path in the HTML output for the 404 page points to a folder called `images`:

```
<img alt="Custom 404" src="/foo/1.0/images/foo.png" />
```

Instead of the image, the alternate text appears in the HTML of the 404 page. Any pointers for me?

**Comment by stsewd** [comment]
Can you share your full `conf.py` file?

**Comment by acozine** [comment]
@stsewd thanks for the quick reply! The conf.py on this branch is at https://github.com/acozine/ansible/blob/custom-404/docs/docsite/rst/conf.py.

**Comment by stsewd** [comment]
Also, can you try installing the extension from master? (I think there was a fix for this)

**Comment by acozine** [comment]
Hm. when I do `pip install --force-reinstall --user git+git://github.com/rtfd/sphinx-notfound-page@master` it re-installs Sphinx 2.x again, and if I try to build with that version, I get:
```
Sphinx parallel build error:
RecursionError: maximum recursion depth exceeded
```
With Sphinx 1.7.9 I see the behavior described above. The `src` tag for our logo gets the correct path `/foo/1.0/_static/images` but the `src` for the 404 image gets `/foo/1.0/images/`.

**Comment by humitos** [comment]
If you disable the extension, what's the src resulting in the output page? Does the image load properly?

**Comment by acozine** [comment]
Oh, interesting. If I disable the extension, the image is placed in `_images` and the `src` points to it there.  The other images under the `docs/docsite/rst` tree are there as well. 

We also have images in the `_static/images` folder - those come from our sphinx theme (`docs/docsite/_themes/sphinx_rtd_theme/static/images`).

**Comment by humitos** [comment]
I'm not sure to follow you.

Can you paste what's the HTML tag generated for the image with the extension enabled and what's with it disabled?

**Comment by humitos** [comment]
I was able to reproduce the issue by myself. I created a PR with the example not working at #46 and I will continue the work for the fix there. Thanks for reporting it!
