### ISSUE TITLE
Sidebar links broken

### ISSUE THREAD

**Issue by banesullivan** [rtfd/sphinx-notfound-page#6]
On some pages, the TOC sidebar links do not work. 

For example, go to [this 404 page](http://docs.vtki.org/en/latest/examples/quick/plot-edl.html) (which is an old link to [this example](http://docs.vtki.org/en/latest/examples/quick/plot/plot-edl.html)) in one of my projects now using `sphinx-notfound-page` and try to go to the examples page. Note that only the *Home* link at the top works

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22067021/54703473-7d8c3500-4afe-11e9-88b7-66d7a9479d52.gif)

**Comment by humitos** [comment]
Yes! This is a known issue. Thanks for reporting it.

I invested some time trying to fix it but I wasn't able. I don't know exactly why the links for the sidebar are not using the patched version of the pathto function.

If you have an idea, help on the debugging or even better a PR I'd really appreciate.

**Comment by banesullivan** [comment]
Do you have a good way of hosting the webpages locally so that the 404 redirect works? I do this all the time with mkdocs but not Sphinx

**Comment by humitos** [comment]
@banesullivan nope, I don't.

I just open them with firefox.

**Comment by humitos** [comment]
@banesullivan Hi! I just opened a PR for this issue and it seems it solves it properly. 
Could you please test your project with this PR https://github.com/rtfd/sphinx-notfound-page/pull/8 and give me some feedback? Thanks!

**Comment by humitos** [comment]
Hi! I just released v0.2 that can be installed from PyPI: https://pypi.org/project/sphinx-notfound-page/ and includes a fix for this problem, creating valid and accurate URLs. Check it out!

**Comment by banesullivan** [comment]
Awesome work! Thanks so much!

Sorry for the delay - took a week vacation
