### ISSUE TITLE
Custom 404 Page Content?

### ISSUE THREAD

**Issue by banesullivan** [rtfd/sphinx-notfound-page#7]
Can we add custom text/links to pages people *might* be looking for?

**Comment by humitos** [comment]
Yes, you can define some variables in the conf.py file.

I think it's called "notfound_body" (I'm on the phone now, sorry)

**Comment by banesullivan** [comment]
Do you have a good way of hosting the webpages locally so that the 404 redirect works? I do this all the time with `mkdocs` but not Sphinx

**Comment by humitos** [comment]
The config is called `notfound_context`, it's a dictionary and you want to modify the `body` key. Something like this (showing the default)

```python
    notfound_context = {
        'body': '<h1>Page not found</h1>\n\nThanks for trying.',
    }
```

**Comment by banesullivan** [comment]
Thanks @humitos!
